// 英検5級レベルの単語・問題データ
// EIKEN5_WORDS: { e: 英語, j: いみ, c: カテゴリ }
// EIKEN5_FILL:  { id, q: ( )入りの文, a: 正解, w: まちがい選択肢3つ, j: 日本語訳 }
// EIKEN5_SORT:  { id, j: 日本語, w: 正しい順の単語, end: 文末記号, alt: 別解(任意) }

const EIKEN5_WORDS = [
  // どうぶつ
  { e: "dog", j: "犬", c: "どうぶつ" },
  { e: "cat", j: "ねこ", c: "どうぶつ" },
  { e: "bird", j: "とり", c: "どうぶつ" },
  { e: "fish", j: "さかな", c: "どうぶつ" },
  { e: "rabbit", j: "うさぎ", c: "どうぶつ" },
  { e: "lion", j: "ライオン", c: "どうぶつ" },
  { e: "tiger", j: "トラ", c: "どうぶつ" },
  { e: "bear", j: "クマ", c: "どうぶつ" },
  { e: "elephant", j: "ゾウ", c: "どうぶつ" },
  { e: "monkey", j: "サル", c: "どうぶつ" },
  { e: "horse", j: "うま", c: "どうぶつ" },
  { e: "cow", j: "うし", c: "どうぶつ" },
  { e: "pig", j: "ぶた", c: "どうぶつ" },
  { e: "mouse", j: "ねずみ", c: "どうぶつ" },
  { e: "panda", j: "パンダ", c: "どうぶつ" },
  { e: "penguin", j: "ペンギン", c: "どうぶつ" },
  { e: "koala", j: "コアラ", c: "どうぶつ" },
  { e: "frog", j: "カエル", c: "どうぶつ" },

  // たべもの・のみもの
  { e: "apple", j: "りんご", c: "たべもの" },
  { e: "orange", j: "オレンジ", c: "たべもの" },
  { e: "banana", j: "バナナ", c: "たべもの" },
  { e: "lemon", j: "レモン", c: "たべもの" },
  { e: "peach", j: "もも", c: "たべもの" },
  { e: "strawberry", j: "いちご", c: "たべもの" },
  { e: "cherry", j: "さくらんぼ", c: "たべもの" },
  { e: "melon", j: "メロン", c: "たべもの" },
  { e: "grape", j: "ぶどう", c: "たべもの" },
  { e: "tomato", j: "トマト", c: "たべもの" },
  { e: "potato", j: "じゃがいも", c: "たべもの" },
  { e: "onion", j: "たまねぎ", c: "たべもの" },
  { e: "carrot", j: "にんじん", c: "たべもの" },
  { e: "egg", j: "たまご", c: "たべもの" },
  { e: "milk", j: "ぎゅうにゅう", c: "たべもの" },
  { e: "juice", j: "ジュース", c: "たべもの" },
  { e: "water", j: "水", c: "たべもの" },
  { e: "tea", j: "おちゃ・こうちゃ", c: "たべもの" },
  { e: "coffee", j: "コーヒー", c: "たべもの" },
  { e: "bread", j: "パン", c: "たべもの" },
  { e: "rice", j: "ごはん・お米", c: "たべもの" },
  { e: "cake", j: "ケーキ", c: "たべもの" },
  { e: "ice cream", j: "アイスクリーム", c: "たべもの" },
  { e: "pizza", j: "ピザ", c: "たべもの" },
  { e: "salad", j: "サラダ", c: "たべもの" },
  { e: "soup", j: "スープ", c: "たべもの" },
  { e: "sandwich", j: "サンドイッチ", c: "たべもの" },
  { e: "hamburger", j: "ハンバーガー", c: "たべもの" },
  { e: "curry", j: "カレー", c: "たべもの" },
  { e: "cookie", j: "クッキー", c: "たべもの" },
  { e: "candy", j: "あめ(おかし)", c: "たべもの" },
  { e: "chocolate", j: "チョコレート", c: "たべもの" },
  { e: "cheese", j: "チーズ", c: "たべもの" },
  { e: "meat", j: "肉", c: "たべもの" },
  { e: "fruit", j: "くだもの", c: "たべもの" },
  { e: "vegetable", j: "やさい", c: "たべもの" },
  { e: "breakfast", j: "あさごはん", c: "たべもの" },
  { e: "lunch", j: "ひるごはん", c: "たべもの" },
  { e: "dinner", j: "ばんごはん", c: "たべもの" },
  { e: "food", j: "たべもの", c: "たべもの" },

  // がっこう
  { e: "school", j: "学校", c: "がっこう" },
  { e: "teacher", j: "先生", c: "がっこう" },
  { e: "student", j: "生徒", c: "がっこう" },
  { e: "class", j: "クラス・じゅぎょう", c: "がっこう" },
  { e: "classroom", j: "きょうしつ", c: "がっこう" },
  { e: "homework", j: "しゅくだい", c: "がっこう" },
  { e: "test", j: "テスト", c: "がっこう" },
  { e: "book", j: "本", c: "がっこう" },
  { e: "notebook", j: "ノート", c: "がっこう" },
  { e: "pencil", j: "えんぴつ", c: "がっこう" },
  { e: "pen", j: "ペン", c: "がっこう" },
  { e: "eraser", j: "けしゴム", c: "がっこう" },
  { e: "ruler", j: "じょうぎ", c: "がっこう" },
  { e: "desk", j: "つくえ", c: "がっこう" },
  { e: "chair", j: "いす", c: "がっこう" },
  { e: "bag", j: "かばん", c: "がっこう" },
  { e: "library", j: "としょかん", c: "がっこう" },
  { e: "gym", j: "たいいくかん", c: "がっこう" },
  { e: "English", j: "えいご", c: "がっこう" },
  { e: "math", j: "さんすう", c: "がっこう" },
  { e: "science", j: "りか", c: "がっこう" },
  { e: "music", j: "おんがく", c: "がっこう" },
  { e: "art", j: "ずこう・びじゅつ", c: "がっこう" },
  { e: "friend", j: "ともだち", c: "がっこう" },
  { e: "club", j: "クラブ", c: "がっこう" },
  { e: "question", j: "しつもん", c: "がっこう" },
  { e: "answer", j: "こたえ", c: "がっこう" },
  { e: "picture", j: "え・しゃしん", c: "がっこう" },
  { e: "map", j: "ちず", c: "がっこう" },
  { e: "name", j: "なまえ", c: "がっこう" },
  { e: "number", j: "かず・ばんごう", c: "がっこう" },
  { e: "word", j: "たんご・ことば", c: "がっこう" },
  { e: "letter", j: "手紙", c: "がっこう" },
  { e: "page", j: "ページ", c: "がっこう" },

  // ひと・かぞく
  { e: "family", j: "かぞく", c: "ひと" },
  { e: "father", j: "お父さん", c: "ひと" },
  { e: "mother", j: "お母さん", c: "ひと" },
  { e: "brother", j: "きょうだい(男)", c: "ひと" },
  { e: "sister", j: "きょうだい(女)", c: "ひと" },
  { e: "grandfather", j: "おじいさん", c: "ひと" },
  { e: "grandmother", j: "おばあさん", c: "ひと" },
  { e: "uncle", j: "おじさん", c: "ひと" },
  { e: "aunt", j: "おばさん", c: "ひと" },
  { e: "cousin", j: "いとこ", c: "ひと" },
  { e: "baby", j: "あかちゃん", c: "ひと" },
  { e: "boy", j: "男の子", c: "ひと" },
  { e: "girl", j: "女の子", c: "ひと" },
  { e: "man", j: "男の人", c: "ひと" },
  { e: "woman", j: "女の人", c: "ひと" },
  { e: "children", j: "子どもたち", c: "ひと" },
  { e: "people", j: "人びと", c: "ひと" },
  { e: "doctor", j: "いしゃ", c: "ひと" },
  { e: "nurse", j: "かんごし", c: "ひと" },
  { e: "pilot", j: "パイロット", c: "ひと" },
  { e: "singer", j: "かしゅ", c: "ひと" },
  { e: "king", j: "王さま", c: "ひと" },
  { e: "queen", j: "女王さま", c: "ひと" },

  // スポーツ・あそび
  { e: "sport", j: "スポーツ", c: "スポーツ・あそび" },
  { e: "baseball", j: "やきゅう", c: "スポーツ・あそび" },
  { e: "soccer", j: "サッカー", c: "スポーツ・あそび" },
  { e: "tennis", j: "テニス", c: "スポーツ・あそび" },
  { e: "basketball", j: "バスケットボール", c: "スポーツ・あそび" },
  { e: "volleyball", j: "バレーボール", c: "スポーツ・あそび" },
  { e: "swimming", j: "すいえい", c: "スポーツ・あそび" },
  { e: "ball", j: "ボール", c: "スポーツ・あそび" },
  { e: "racket", j: "ラケット", c: "スポーツ・あそび" },
  { e: "team", j: "チーム", c: "スポーツ・あそび" },
  { e: "game", j: "ゲーム・しあい", c: "スポーツ・あそび" },
  { e: "player", j: "せんしゅ", c: "スポーツ・あそび" },
  { e: "song", j: "うた", c: "スポーツ・あそび" },
  { e: "piano", j: "ピアノ", c: "スポーツ・あそび" },
  { e: "guitar", j: "ギター", c: "スポーツ・あそび" },
  { e: "violin", j: "バイオリン", c: "スポーツ・あそび" },
  { e: "movie", j: "えいが", c: "スポーツ・あそび" },
  { e: "TV", j: "テレビ", c: "スポーツ・あそび" },
  { e: "camera", j: "カメラ", c: "スポーツ・あそび" },
  { e: "computer", j: "コンピューター", c: "スポーツ・あそび" },
  { e: "phone", j: "でんわ", c: "スポーツ・あそび" },
  { e: "comic book", j: "まんが", c: "スポーツ・あそび" },
  { e: "toy", j: "おもちゃ", c: "スポーツ・あそび" },
  { e: "doll", j: "にんぎょう", c: "スポーツ・あそび" },

  // いえ・もちもの
  { e: "house", j: "いえ", c: "いえ・もちもの" },
  { e: "room", j: "へや", c: "いえ・もちもの" },
  { e: "kitchen", j: "だいどころ", c: "いえ・もちもの" },
  { e: "door", j: "ドア", c: "いえ・もちもの" },
  { e: "window", j: "まど", c: "いえ・もちもの" },
  { e: "table", j: "テーブル", c: "いえ・もちもの" },
  { e: "bed", j: "ベッド", c: "いえ・もちもの" },
  { e: "box", j: "はこ", c: "いえ・もちもの" },
  { e: "cup", j: "コップ・カップ", c: "いえ・もちもの" },
  { e: "clock", j: "とけい", c: "いえ・もちもの" },
  { e: "umbrella", j: "かさ", c: "いえ・もちもの" },
  { e: "hat", j: "ぼうし", c: "いえ・もちもの" },
  { e: "cap", j: "キャップ(やきゅうぼう)", c: "いえ・もちもの" },
  { e: "shirt", j: "シャツ", c: "いえ・もちもの" },
  { e: "T-shirt", j: "Tシャツ", c: "いえ・もちもの" },
  { e: "sweater", j: "セーター", c: "いえ・もちもの" },
  { e: "coat", j: "コート", c: "いえ・もちもの" },
  { e: "shoes", j: "くつ", c: "いえ・もちもの" },
  { e: "socks", j: "くつした", c: "いえ・もちもの" },
  { e: "gloves", j: "てぶくろ", c: "いえ・もちもの" },
  { e: "dress", j: "ドレス・ワンピース", c: "いえ・もちもの" },
  { e: "skirt", j: "スカート", c: "いえ・もちもの" },
  { e: "pocket", j: "ポケット", c: "いえ・もちもの" },
  { e: "garden", j: "にわ", c: "いえ・もちもの" },
  { e: "present", j: "プレゼント", c: "いえ・もちもの" },

  // まち・のりもの
  { e: "park", j: "こうえん", c: "まち・のりもの" },
  { e: "zoo", j: "どうぶつえん", c: "まち・のりもの" },
  { e: "station", j: "えき", c: "まち・のりもの" },
  { e: "hospital", j: "びょういん", c: "まち・のりもの" },
  { e: "store", j: "みせ", c: "まち・のりもの" },
  { e: "restaurant", j: "レストラン", c: "まち・のりもの" },
  { e: "supermarket", j: "スーパーマーケット", c: "まち・のりもの" },
  { e: "post office", j: "ゆうびんきょく", c: "まち・のりもの" },
  { e: "airport", j: "くうこう", c: "まち・のりもの" },
  { e: "city", j: "し(大きな まち)", c: "まち・のりもの" },
  { e: "town", j: "まち", c: "まち・のりもの" },
  { e: "street", j: "とおり・みち", c: "まち・のりもの" },
  { e: "car", j: "くるま", c: "まち・のりもの" },
  { e: "bus", j: "バス", c: "まち・のりもの" },
  { e: "train", j: "でんしゃ", c: "まち・のりもの" },
  { e: "plane", j: "ひこうき", c: "まち・のりもの" },
  { e: "ship", j: "ふね", c: "まち・のりもの" },
  { e: "boat", j: "ボート", c: "まち・のりもの" },
  { e: "taxi", j: "タクシー", c: "まち・のりもの" },
  { e: "bike", j: "じてんしゃ", c: "まち・のりもの" },

  // しぜん・てんき
  { e: "mountain", j: "山", c: "しぜん" },
  { e: "river", j: "川", c: "しぜん" },
  { e: "sea", j: "うみ", c: "しぜん" },
  { e: "beach", j: "はまべ・ビーチ", c: "しぜん" },
  { e: "sky", j: "そら", c: "しぜん" },
  { e: "sun", j: "たいよう", c: "しぜん" },
  { e: "moon", j: "(そらの)月", c: "しぜん" },
  { e: "star", j: "ほし", c: "しぜん" },
  { e: "rain", j: "雨", c: "しぜん" },
  { e: "snow", j: "ゆき", c: "しぜん" },
  { e: "flower", j: "花", c: "しぜん" },
  { e: "tree", j: "木", c: "しぜん" },
  { e: "weather", j: "てんき", c: "しぜん" },

  // とき・ようび
  { e: "morning", j: "あさ", c: "とき" },
  { e: "afternoon", j: "ごご", c: "とき" },
  { e: "evening", j: "ゆうがた", c: "とき" },
  { e: "night", j: "よる", c: "とき" },
  { e: "today", j: "きょう", c: "とき" },
  { e: "tomorrow", j: "あした", c: "とき" },
  { e: "week", j: "しゅう(7日間)", c: "とき" },
  { e: "weekend", j: "しゅうまつ", c: "とき" },
  { e: "month", j: "(カレンダーの)月", c: "とき" },
  { e: "year", j: "年(ねん)", c: "とき" },
  { e: "birthday", j: "たんじょうび", c: "とき" },
  { e: "spring", j: "はる", c: "とき" },
  { e: "summer", j: "なつ", c: "とき" },
  { e: "fall", j: "あき", c: "とき" },
  { e: "winter", j: "ふゆ", c: "とき" },
  { e: "Sunday", j: "日よう日", c: "とき" },
  { e: "Monday", j: "月よう日", c: "とき" },
  { e: "Tuesday", j: "火よう日", c: "とき" },
  { e: "Wednesday", j: "水よう日", c: "とき" },
  { e: "Thursday", j: "木よう日", c: "とき" },
  { e: "Friday", j: "金よう日", c: "とき" },
  { e: "Saturday", j: "土よう日", c: "とき" },
  { e: "time", j: "じかん", c: "とき" },
  { e: "day", j: "日・1日", c: "とき" },

  // からだ
  { e: "head", j: "あたま", c: "からだ" },
  { e: "face", j: "かお", c: "からだ" },
  { e: "eye", j: "目", c: "からだ" },
  { e: "ear", j: "耳", c: "からだ" },
  { e: "nose", j: "はな(かおの)", c: "からだ" },
  { e: "mouth", j: "口", c: "からだ" },
  { e: "hand", j: "手", c: "からだ" },
  { e: "foot", j: "あし(あしさき)", c: "からだ" },
  { e: "leg", j: "あし(ふとももから下)", c: "からだ" },
  { e: "hair", j: "かみの毛", c: "からだ" },
  { e: "arm", j: "うで", c: "からだ" },

  // いろ
  { e: "red", j: "赤", c: "いろ" },
  { e: "blue", j: "青", c: "いろ" },
  { e: "yellow", j: "きいろ", c: "いろ" },
  { e: "green", j: "みどり", c: "いろ" },
  { e: "black", j: "黒", c: "いろ" },
  { e: "white", j: "白", c: "いろ" },
  { e: "pink", j: "ピンク", c: "いろ" },
  { e: "purple", j: "むらさき", c: "いろ" },
  { e: "brown", j: "ちゃいろ", c: "いろ" },
  { e: "color", j: "いろ", c: "いろ" },

  // かず
  { e: "one", j: "1(いち)", c: "かず" },
  { e: "two", j: "2(に)", c: "かず" },
  { e: "three", j: "3(さん)", c: "かず" },
  { e: "four", j: "4(よん)", c: "かず" },
  { e: "five", j: "5(ご)", c: "かず" },
  { e: "six", j: "6(ろく)", c: "かず" },
  { e: "seven", j: "7(なな)", c: "かず" },
  { e: "eight", j: "8(はち)", c: "かず" },
  { e: "nine", j: "9(きゅう)", c: "かず" },
  { e: "ten", j: "10(じゅう)", c: "かず" },
  { e: "hundred", j: "100(ひゃく)", c: "かず" },

  // することば(どうし)
  { e: "go", j: "行く", c: "することば" },
  { e: "come", j: "来る", c: "することば" },
  { e: "run", j: "はしる", c: "することば" },
  { e: "walk", j: "あるく", c: "することば" },
  { e: "jump", j: "ジャンプする", c: "することば" },
  { e: "swim", j: "およぐ", c: "することば" },
  { e: "fly", j: "(そらを)とぶ", c: "することば" },
  { e: "eat", j: "たべる", c: "することば" },
  { e: "drink", j: "のむ", c: "することば" },
  { e: "make", j: "つくる", c: "することば" },
  { e: "cook", j: "りょうりする", c: "することば" },
  { e: "play", j: "(スポーツを)する・あそぶ", c: "することば" },
  { e: "study", j: "べんきょうする", c: "することば" },
  { e: "read", j: "よむ", c: "することば" },
  { e: "write", j: "かく", c: "することば" },
  { e: "speak", j: "話す", c: "することば" },
  { e: "talk", j: "おしゃべりする", c: "することば" },
  { e: "listen", j: "(耳をすまして)きく", c: "することば" },
  { e: "look", j: "(ちゅういして)見る", c: "することば" },
  { e: "see", j: "見える", c: "することば" },
  { e: "watch", j: "(テレビなどを)見る", c: "することば" },
  { e: "want", j: "ほしい", c: "することば" },
  { e: "like", j: "すきである", c: "することば" },
  { e: "love", j: "だいすきである", c: "することば" },
  { e: "have", j: "もっている", c: "することば" },
  { e: "get", j: "もらう・手に入れる", c: "することば" },
  { e: "use", j: "つかう", c: "することば" },
  { e: "help", j: "たすける・てつだう", c: "することば" },
  { e: "open", j: "あける", c: "することば" },
  { e: "close", j: "しめる", c: "することば" },
  { e: "wash", j: "あらう", c: "することば" },
  { e: "clean", j: "そうじする", c: "することば" },
  { e: "sing", j: "うたう", c: "することば" },
  { e: "dance", j: "おどる", c: "することば" },
  { e: "sit", j: "すわる", c: "することば" },
  { e: "stand", j: "立つ", c: "することば" },
  { e: "sleep", j: "ねむる", c: "することば" },
  { e: "live", j: "すんでいる", c: "することば" },
  { e: "know", j: "しっている", c: "することば" },
  { e: "meet", j: "会う", c: "することば" },
  { e: "buy", j: "かう", c: "することば" },
  { e: "teach", j: "おしえる", c: "することば" },
  { e: "practice", j: "れんしゅうする", c: "することば" },
  { e: "do", j: "する", c: "することば" },
  { e: "stop", j: "とまる・やめる", c: "することば" },

  // ようすことば(けいようし など)
  { e: "big", j: "大きい", c: "ようすことば" },
  { e: "small", j: "小さい", c: "ようすことば" },
  { e: "long", j: "ながい", c: "ようすことば" },
  { e: "short", j: "みじかい", c: "ようすことば" },
  { e: "tall", j: "(せが)高い", c: "ようすことば" },
  { e: "old", j: "ふるい・年上の", c: "ようすことば" },
  { e: "new", j: "あたらしい", c: "ようすことば" },
  { e: "young", j: "わかい", c: "ようすことば" },
  { e: "good", j: "よい", c: "ようすことば" },
  { e: "nice", j: "すてきな", c: "ようすことば" },
  { e: "fine", j: "げんきな", c: "ようすことば" },
  { e: "great", j: "すばらしい", c: "ようすことば" },
  { e: "happy", j: "うれしい", c: "ようすことば" },
  { e: "sad", j: "かなしい", c: "ようすことば" },
  { e: "hungry", j: "おなかが すいた", c: "ようすことば" },
  { e: "sleepy", j: "ねむい", c: "ようすことば" },
  { e: "busy", j: "いそがしい", c: "ようすことば" },
  { e: "fast", j: "はやい", c: "ようすことば" },
  { e: "slow", j: "おそい", c: "ようすことば" },
  { e: "hot", j: "あつい", c: "ようすことば" },
  { e: "cold", j: "さむい・つめたい", c: "ようすことば" },
  { e: "warm", j: "あたたかい", c: "ようすことば" },
  { e: "cool", j: "すずしい", c: "ようすことば" },
  { e: "sunny", j: "はれの", c: "ようすことば" },
  { e: "rainy", j: "雨ふりの", c: "ようすことば" },
  { e: "cloudy", j: "くもりの", c: "ようすことば" },
  { e: "easy", j: "かんたんな", c: "ようすことば" },
  { e: "pretty", j: "きれいな", c: "ようすことば" },
  { e: "cute", j: "かわいい", c: "ようすことば" },
  { e: "beautiful", j: "うつくしい", c: "ようすことば" },
  { e: "kind", j: "やさしい", c: "ようすことば" },
  { e: "favorite", j: "いちばん すきな", c: "ようすことば" },
  { e: "many", j: "たくさんの", c: "ようすことば" },
  { e: "very", j: "とても", c: "ようすことば" },
  { e: "now", j: "いま", c: "ようすことば" },
  { e: "here", j: "ここ", c: "ようすことば" },
  { e: "there", j: "そこ", c: "ようすことば" },
  { e: "together", j: "いっしょに", c: "ようすことば" },
  { e: "often", j: "よく(ひんぱんに)", c: "ようすことば" },
  { e: "sometimes", j: "ときどき", c: "ようすことば" },
  { e: "usually", j: "たいてい", c: "ようすことば" }
];

// あなうめ問題(英検5級の大問1・2ふう)
const EIKEN5_FILL = [
  { id: "f01", q: "I ( ) a student.", a: "am", w: ["is", "are", "do"], j: "わたしは 生徒です。" },
  { id: "f02", q: "You ( ) tall.", a: "are", w: ["am", "is", "does"], j: "あなたは せが高いね。" },
  { id: "f03", q: "This ( ) my book.", a: "is", w: ["am", "are", "do"], j: "これは わたしの本です。" },
  { id: "f04", q: "Ken and I ( ) good friends.", a: "are", w: ["is", "am", "be"], j: "ケンとわたしは なかよしです。" },
  { id: "f05", q: "I ( ) tennis every day.", a: "play", w: ["eat", "drink", "open"], j: "わたしは 毎日テニスをします。" },
  { id: "f06", q: "My father ( ) breakfast on Sundays.", a: "cooks", w: ["cook", "cooking", "to cook"], j: "お父さんは 日曜日にあさごはんを作ります。" },
  { id: "f07", q: "Emi ( ) to school by bus.", a: "goes", w: ["go", "going", "to go"], j: "エミは バスで学校に行きます。" },
  { id: "f08", q: "I ( ) up at seven every morning.", a: "get", w: ["make", "sit", "do"], j: "わたしは 毎朝7時におきます。" },
  { id: "f09", q: "We ( ) English at school.", a: "study", w: ["listen", "open", "wash"], j: "わたしたちは 学校でえいごをべんきょうします。" },
  { id: "f10", q: "( ) you like dogs?", a: "Do", w: ["Does", "Are", "Is"], j: "あなたは 犬がすきですか?" },
  { id: "f11", q: "( ) Ken play the piano?", a: "Does", w: ["Do", "Is", "Are"], j: "ケンは ピアノをひきますか?" },
  { id: "f12", q: "I ( ) like soccer.", a: "don't", w: ["isn't", "aren't", "doesn't"], j: "わたしは サッカーがすきではありません。" },
  { id: "f13", q: "My sister can ( ) very fast.", a: "run", w: ["runs", "running", "to run"], j: "わたしのおねえさんは とてもはやく走れます。" },
  { id: "f14", q: "Can you ( ) the guitar?", a: "play", w: ["plays", "playing", "player"], j: "あなたは ギターをひけますか?" },
  { id: "f15", q: "I'm ( ) TV now.", a: "watching", w: ["watch", "watches", "to watch"], j: "わたしは いまテレビを見ています。" },
  { id: "f16", q: "Look! Birds are ( ) in the sky.", a: "flying", w: ["fly", "flies", "to fly"], j: "見て!とりが そらをとんでいるよ。" },
  { id: "f17", q: "( ) old are you?", a: "How", w: ["What", "Who", "When"], j: "あなたは なんさいですか?" },
  { id: "f18", q: "( ) is your birthday?", a: "When", w: ["Who", "Where", "How"], j: "あなたの たんじょうびはいつですか?" },
  { id: "f19", q: "( ) is my cap? — It's on the bed.", a: "Where", w: ["When", "Who", "What"], j: "ぼくのぼうしは どこ? ― ベッドの上だよ。" },
  { id: "f20", q: "( ) is that boy? — He's my brother.", a: "Who", w: ["What", "Where", "When"], j: "あの男の子は だれ? ― わたしのおとうとだよ。" },
  { id: "f21", q: "( ) time is it now?", a: "What", w: ["Who", "Where", "How"], j: "いま なんじですか?" },
  { id: "f22", q: "( ) do you like, cats or dogs?", a: "Which", w: ["Who", "When", "Where"], j: "ねこと犬、どちらが すきですか?" },
  { id: "f23", q: "( ) open the window.", a: "Please", w: ["Do", "Does", "Is"], j: "まどを あけてください。" },
  { id: "f24", q: "Let's ( ) to the park.", a: "go", w: ["goes", "going", "to go"], j: "こうえんに 行こうよ。" },
  { id: "f25", q: "( ) run in the classroom.", a: "Don't", w: ["Isn't", "Aren't", "Doesn't"], j: "きょうしつで 走ってはいけません。" },
  { id: "f26", q: "I have two ( ).", a: "cats", w: ["cat", "a cat", "milk"], j: "わたしは ねこを2ひきかっています。" },
  { id: "f27", q: "She is ( ) mother.", a: "my", w: ["I", "me", "we"], j: "かのじょは わたしのお母さんです。" },
  { id: "f28", q: "( ) name is Tom.", a: "His", w: ["He", "Him", "She"], j: "かれの なまえはトムです。" },
  { id: "f29", q: "We play baseball ( ) Sundays.", a: "on", w: ["in", "at", "of"], j: "わたしたちは 日曜日にやきゅうをします。" },
  { id: "f30", q: "I go to bed ( ) ten.", a: "at", w: ["on", "in", "under"], j: "わたしは 10時にねます。" },
  { id: "f31", q: "She lives ( ) Tokyo.", a: "in", w: ["on", "at", "to"], j: "かのじょは とうきょうにすんでいます。" },
  { id: "f32", q: "Let's go ( ) the zoo.", a: "to", w: ["of", "on", "in"], j: "どうぶつえんに 行こうよ。" },
  { id: "f33", q: "Look ( ) this picture.", a: "at", w: ["in", "on", "of"], j: "このえを 見て。" },
  { id: "f34", q: "I listen ( ) music every night.", a: "to", w: ["at", "of", "on"], j: "わたしは 毎ばんおんがくをききます。" },
  { id: "f35", q: "A cup ( ) tea, please.", a: "of", w: ["to", "at", "on"], j: "こうちゃを 1ぱいください。" },
  { id: "f36", q: "A: How are you?  B: I'm ( ), thank you.", a: "fine", w: ["fast", "tall", "rainy"], j: "A: げんき? B: げんきだよ、ありがとう。" },
  { id: "f37", q: "A: Do you like music?  B: Yes, I ( ).", a: "do", w: ["am", "does", "is"], j: "A: おんがくすき? B: うん、すきだよ。" },
  { id: "f38", q: "A: Is this your bag?  B: No, it ( ).", a: "isn't", w: ["is", "don't", "aren't"], j: "A: これはあなたのかばん? B: ちがうよ。" },
  { id: "f39", q: "A: Can your brother swim?  B: Yes, he ( ).", a: "can", w: ["is", "does", "do"], j: "A: おにいさんはおよげる? B: うん、およげるよ。" },
  { id: "f40", q: "A: Thank you very much.  B: You're ( ).", a: "welcome", w: ["fine", "happy", "good"], j: "A: どうもありがとう。 B: どういたしまして。" },
  { id: "f41", q: "A: Nice to ( ) you.  B: Nice to meet you, too.", a: "meet", w: ["eat", "make", "take"], j: "A: はじめまして。 B: こちらこそ、はじめまして。" },
  { id: "f42", q: "A: ( ) many pencils do you have?  B: Five.", a: "How", w: ["What", "Who", "Which"], j: "A: えんぴつを何本もってる? B: 5本だよ。" },
  { id: "f43", q: "A: What ( ) do you like?  B: I like blue.", a: "color", w: ["sport", "food", "animal"], j: "A: 何いろがすき? B: 青がすきだよ。" },
  { id: "f44", q: "A: Where ( ) you live?  B: In Osaka.", a: "do", w: ["are", "is", "does"], j: "A: どこにすんでるの? B: おおさかだよ。" }
];

// ならべかえ問題(英検5級の大問3ふう)
const EIKEN5_SORT = [
  { id: "s01", j: "わたしは ねこが すきです。", w: ["I", "like", "cats"], end: "." },
  { id: "s02", j: "これは わたしの 本です。", w: ["This", "is", "my", "book"], end: "." },
  { id: "s03", j: "あなたは テニスを しますか?", w: ["Do", "you", "play", "tennis"], end: "?" },
  { id: "s04", j: "わたしの お父さんは 先生です。", w: ["My", "father", "is", "a", "teacher"], end: "." },
  { id: "s05", j: "わたしたちは よい ともだちです。", w: ["We", "are", "good", "friends"], end: "." },
  { id: "s06", j: "ケンは じょうずに およげます。", w: ["Ken", "can", "swim", "well"], end: "." },
  { id: "s07", j: "ドアを あけてください。", w: ["Please", "open", "the", "door"], end: "." },
  { id: "s08", j: "いっしょに うたいましょう。", w: ["Let's", "sing", "together"], end: "." },
  { id: "s09", j: "わたしは 犬を 2ひき かっています。", w: ["I", "have", "two", "dogs"], end: "." },
  { id: "s10", j: "あなたの たんじょうびは いつですか?", w: ["When", "is", "your", "birthday"], end: "?" },
  { id: "s11", j: "あの 男の子は だれですか?", w: ["Who", "is", "that", "boy"], end: "?" },
  { id: "s12", j: "わたしは いま テレビを 見ています。", w: ["I", "am", "watching", "TV", "now"], end: ".", alt: ["I am now watching TV"] },
  { id: "s13", j: "ここで 走っては いけません。", w: ["Don't", "run", "here"], end: "." },
  { id: "s14", j: "わたしは バスで 学校に 行きます。", w: ["I", "go", "to", "school", "by", "bus"], end: "." },
  { id: "s15", j: "いま なんじですか?", w: ["What", "time", "is", "it", "now"], end: "?" },
  { id: "s16", j: "わたしは あさごはんに パンを たべます。", w: ["I", "eat", "bread", "for", "breakfast"], end: "." },
  { id: "s17", j: "あなたは どこに すんでいますか?", w: ["Where", "do", "you", "live"], end: "?" },
  { id: "s18", j: "わたしの ねこは とても かわいいです。", w: ["My", "cat", "is", "very", "cute"], end: "." },
  { id: "s19", j: "トムは 毎日 ピアノを ひきます。", w: ["Tom", "plays", "the", "piano", "every", "day"], end: "." },
  { id: "s20", j: "あれは なんですか?", w: ["What", "is", "that"], end: "?" },
  { id: "s21", j: "この 花は うつくしいです。", w: ["This", "flower", "is", "beautiful"], end: "." },
  { id: "s22", j: "わたしは 10さいです。", w: ["I", "am", "ten", "years", "old"], end: "." },
  { id: "s23", j: "わたしの お母さんは 花が すきです。", w: ["My", "mother", "likes", "flowers"], end: "." },
  { id: "s24", j: "こうえんに 行きましょう。", w: ["Let's", "go", "to", "the", "park"], end: "." }
];
